# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  AX_12A_04_1_dof5:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0
  AX_12A_04_2_Revolute_86:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0
  AX_12A_04_3_Revolute_75:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0
  AX_12A_04_4_Revolute_90:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0
  Nema_34_v3_dof2:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0
  STEPPER_MOTOR_dof3:
    has_velocity_limits: true
    max_velocity: 1000000.0
    has_acceleration_limits: false
    max_acceleration: 0
  firstDOF_final_dof1:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0
  gcomp1_Revolute_63:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0